# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42afedf1991a7172a300c389f1c95dd07d693a79075b9fa4208d003affc55b2deff8af8468dbe7a4a3c1ba42a928f419fc24104973cdd33ba05e267b995934a1

test:
  secret_key_base: 2a18f0d2d137e45ccadcdc7fe408b0f40412e73cc6ce386f84672db8e40b41a31c04373d2027e7fa906dc614d1a51dc97ae2e8cf44df72cb97c49ee5ff9613fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
